.github/workflows/spec.yml:
  unmanaged: false
.travis.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.gitignore:
  required: &ignorepaths
    - '**/litmus_inventory.yaml'
.rubocop.yml:
  default_configs:
   Style/ClassAndModuleChildren:
     Description: Nested Style Allows Namespaced Classes.
     EnforcedStyle: nested